### ISSUE TITLE
`per-file-ignores` doesn't seem to be working

### ISSUE THREAD

**Issue by jacobmischka** [python-lsp/python-lsp-ruff#5]
~~This works in both `ruff` via CLI and with `python-lsp-ruff`; none of the listed errors are visible in `__init__.py` files:~~

*Edit*: No it doesn't, please see comment below.

```toml
[tool.ruff]
ignore = [
	"E501", # line length violations
	"E722", # bare except
]
per-file-ignores = {
	# Ignore import violations in all `__init__.py` files
	"__init__.py" = ["E402", "F401", "F403"]
}
```

This works when invoking `ruff` via CLI, but not in `python-lsp-ruff`; the per-file-ignores are visible in the editor but not in the command line (the global `ignore`d errors are still invisible in both):

```toml
[tool.ruff]
ignore = [
	"E501", # line length violations
	"E722", # bare except
]

# Ignore import violations in all `__init__.py` files
[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403"]
```

It seems like `python-lsp-ruff` doesn't parse sub-tables specified via headers somehow?

Thank you for this project!

**Comment by jacobmischka** [comment]
Er, just kidding, the former example is invalid toml, so ruff was just not working at all apparently.

This also doesn't work:

```toml
[tool.ruff]
ignore = [
	"E501", # line length violations
	"E722", # bare except
]
per-file-ignores = { "__init__.py" = ["E402", "F401", "F403"] }
```

So it seems like per-file-ignores is not working for me in `python-lsp-ruff` at all.
